apiVersion: v1
kind: Secret
metadata:
  name: airflow-service-secrets
  namespace: airflow-service
type: Opaque
data:
  airflow-fernet-key: "WmNxSnBLRWNGMzc4ampBZ2doYWhHTmlGaXllUnZDTEFCWTJteWdLQkstbz0="
  airflow-sql-alchemy-conn: "cG9zdGdyZXNxbDovL2FpcmZsb3c6dGhpc19pc19ub3RfdmVyeV9zZWN1cmVAYWlyZmxvdy1kYjo1NDMyL2FpcmZsb3c="
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-web-secrets
  namespace: airflow-service
type: Opaque
data:
  airflow-flask-secret-key: "OTQxMmViMDE3Yzk2NGIzODg4YTRkNzdhOGZmNzI5YjU="
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-task-secrets
  namespace: airflow-task
type: Opaque
data:
  airflow-fernet-key: "WmNxSnBLRWNGMzc4ampBZ2doYWhHTmlGaXllUnZDTEFCWTJteWdLQkstbz0="
  airflow-sql-alchemy-conn: "cG9zdGdyZXNxbDovL2FpcmZsb3c6dGhpc19pc19ub3RfdmVyeV9zZWN1cmVAYWlyZmxvdy1kYjo1NDMyL2FpcmZsb3c="
